# CircleCI 2.0 configuration file

version: 2
jobs:
  build-python36:
    docker:
      - image: python:alpine3.6
    environment:
      - PYTHONPATH: python
      - AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run:
          name: install system dependencies
          command: apk add --update-cache gcc musl-dev libffi-dev openssl-dev
      - run:
          name: install python dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest pytest-cov moto
      - run:
          name: run tests
          command: pytest --cov-report term-missing --cov=index tests

workflows:
  version: 2
  build:
    jobs:
      - build-python36
